### ISSUE TITLE
大佬你好，一言模块怎么关掉？

### ISSUE THREAD

**Issue by swh922** [hmhm2022/Card-Tab#10]

**Comment by hmhm2022** [comment]
<p id="hitokoto">
                <a href="#" id="hitokoto_text"></a>
            </p>
            <script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>
          把380-384行的这几句给删除掉

**Comment by swh922** [comment]
>             
>             <p id="hitokoto">
>                 <a href="#" id="hitokoto_text"></a>
>             </p>
>             <script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>
>           把380-384行的这几句给删除掉

谢谢🙏
