### ISSUE TITLE
注意！这个项目的密码验证和私密书签完全在前端实现

### ISSUE THREAD

**Issue by molikai-work** [hmhm2022/Card-Tab#4]
即使在未登录的情况下，api依然返回所有数据，是前端根据登陆状态决定是否显示或者隐藏：
![image](https://github.com/user-attachments/assets/71f24fcd-7331-4978-8276-58467d377496)

在后端代码中仅在`verifyPassword`端口做了密码验证，`saveOrder`完全没有安全验证或者其他验证措施，
```
if (url.pathname === '/api/saveOrder' && request.method === 'POST') {
    const { userId, links, categories } = await request.json();
    await env.CARD_ORDER.put(userId, JSON.stringify({ links, categories }));
    return new Response(JSON.stringify({ success: true }), { status: 200 });
}

if (url.pathname === '/api/verifyPassword' && request.method === 'POST') {
    const { password } = await request.json();
    const isValid = password === env.ADMIN_PASSWORD;
    return new Response(JSON.stringify({ valid: isValid }), {
        status: isValid ? 200 : 403,
        headers: { 'Content-Type': 'application/json' },
    });
}
```

要做的更改例如：
1. 在`getLinks`添加验证，并添加处理措施，如果在请求中未包含正确的密码字段则只返回可公开的数据。
2. 在`saveOrder`添加验证，只有在提供正确的密码之后才能继续处理数据，否则拒绝。

---
优化建议，不要将前端文件直接放在后端代码中供访问主页时返回，
可以将前端文件放在远程地址，例如github存储库，
然后在返回函数改为使用`fetch`请求远程地址并返回，
示例：
```
if (url.pathname === '/') {
    return fetch('https://example.github.io/Card-Tab/')
        .then(response => {
            if (!response.ok) {
                throw new Error('网络响应不正常');
            }
            return response.text();
        })
        .then(htmlContent => {
            return new Response(htmlContent, {
                headers: { 'Content-Type': 'text/html' }
            });
        })
        .catch(error => {
            return new Response('获取 HTML 内容时出错', {
                status: 500
            });
        });
}
```

**Comment by hmhm2022** [comment]
感谢指导，其实我是前端小白，属于是有了个想法以后 边干边学的。
只关注界面和功能优化了，确实在安全方面埋了坑，这个后面会考虑你的建议。
我最初的想法就是做一个轻量化容易上手，对于纯小白特别友好的书签导航页，力求简单，所以前后端分离我不太会考虑。
基于以上，特别注重隐私的朋友请谨慎将你的私密链接放置到本项目中，并建议部署了项目的朋友备份好自己的书签（直接到KV里 拷贝出来即可）

**Comment by h20see** [comment]
使用cf自带域名，xx.xx.dev/api/getLinks?userId=testUser确实会输出全部书签，停用cf自带域名使用个人域名，个人域名/api/getLinks?userId=testUser就不会输出书签了，网页显示书签也正常，貌似是隐藏成功的

**Comment by hmhm2022** [comment]
已经添加对 getLinks 和 saveOrder 的验证
